name: Check

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Check
        run: ./gradlew check --warning-mode all
